<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Company;
use Carbon\Carbon;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $currentTimeStamp = Carbon::now();
        Company::insert([
            ['name' => 'Bethesda Softworks', 'role' => 'publisher', 'image' => '01.png', 'description' => 'Bethesda Softworks, founded in 1986, is a leading video game publisher known for iconic franchises like The Elder Scrolls, Fallout, and Doom. The company is renowned for creating vast, open-world RPGs and delivering immersive storytelling, deep lore, and player freedom, shaping the gaming industry for decades.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Bethesda Game Studios', 'role' => 'developer', 'image' => '02.png', 'description' => 'Bethesda Game Studios, a subsidiary of Bethesda Softworks, is the developer behind some of the most influential RPGs, including The Elder Scrolls series and Fallout 3. Their games are known for vast open worlds, player-driven narratives, and innovative design, making them a powerhouse in the RPG genre.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Sony Interactive Entertainment', 'role' => 'publisher', 'image' => '03.jpg', 'description' => 'Sony Interactive Entertainment (SIE) is a global leader in video game development and publishing, responsible for the PlayStation console line. SIE produces high-quality first-party games, such as The Last of Us and God of War, while also managing the PlayStation Network and PlayStation Plus services.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Insomniac Games', 'role' => 'developer', 'image' => '04.png', 'description' => 'Insomniac Games, founded in 1994, is known for creating engaging action-adventure games, including Spyro the Dragon, Ratchet & Clank, and Spider-Man for PlayStation. Their creative storytelling, technical innovation, and dynamic gameplay have made them a top-tier developer under Sony Interactive Entertainment\'s umbrella.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Sony Computer Entertainment', 'role' => 'publisher', 'image' => '05.jpg', 'description' => 'Sony Computer Entertainment (SCE), now known as Sony Interactive Entertainment, was founded in 1993 to oversee PlayStation console development and publishing. SCE introduced groundbreaking hardware like the PlayStation and PlayStation 2, revolutionizing the gaming industry by focusing on high-quality gaming experiences and innovative technologies.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Naughty Dog', 'role' => 'developer', 'image' => '06.png', 'description' => 'Naughty Dog, established in 1984, is renowned for creating story-driven action-adventure games. They developed critically acclaimed titles such as Uncharted and The Last of Us, showcasing exceptional storytelling, character development, and innovative gameplay. Naughty Dog is a key player in the PlayStation ecosystem.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Roblox Corporation', 'role' => 'publisher', 'image' => '07.jpeg', 'description' => 'Roblox Corporation is a developer and publisher of the massively popular online game creation platform, Roblox. Launched in 2006, the platform allows users to create, share, and play games made by others. Roblox has become a global sensation, offering a virtual world of endless user-generated experiences.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Roblox Corporation', 'role' => 'developer', 'image' => '07.jpeg', 'description' => 'Roblox Corporation is a developer and publisher of the massively popular online game creation platform, Roblox. Launched in 2006, the platform allows users to create, share, and play games made by others. Roblox has become a global sensation, offering a virtual world of endless user-generated experiences.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Riot Games', 'role' => 'publisher', 'image' => '08.jpg', 'description' => 'Riot Games, founded in 2006, is best known for developing League of Legends, one of the world\'s most popular multiplayer online battle arena (MOBA) games. Riot continues to expand its universe, releasing titles like Valorant, while also organizing global esports events and maintaining a strong player community.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Riot Games', 'role' => 'developer', 'image' => '08.jpg', 'description' => 'Riot Games, founded in 2006, is best known for developing League of Legends, one of the world\'s most popular multiplayer online battle arena (MOBA) games. Riot continues to expand its universe, releasing titles like Valorant, while also organizing global esports events and maintaining a strong player community.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Epic Games', 'role' => 'publisher', 'image' => '09.jpg', 'description' => 'Epic Games, founded in 1991, is a leading developer and publisher, known for creating Unreal Engine and Fortnite. Epic revolutionized gaming with advanced graphics technology and multiplayer gaming. Their free-to-play battle royale game Fortnite has made a massive cultural impact and redefined gaming as a service.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Epic Games', 'role' => 'developer', 'image' => '09.jpg', 'description' => 'Epic Games, founded in 1991, is a leading developer and publisher, known for creating Unreal Engine and Fortnite. Epic revolutionized gaming with advanced graphics technology and multiplayer gaming. Their free-to-play battle royale game Fortnite has made a massive cultural impact and redefined gaming as a service.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Blizzard Entertainment', 'role' => 'publisher', 'image' => '10.jpg', 'description' => 'Blizzard Entertainment, founded in 1991, is renowned for developing genre-defining games such as Warcraft, Diablo, StarCraft, and Overwatch. Blizzard\'s focus on high-quality production values, engaging storytelling, and multiplayer experiences has made them a dominant force in PC gaming and esports.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Blizzard Entertainment', 'role' => 'developer', 'image' => '10.jpg', 'description' => 'Blizzard Entertainment, founded in 1991, is renowned for developing genre-defining games such as Warcraft, Diablo, StarCraft, and Overwatch. Blizzard\'s focus on high-quality production values, engaging storytelling, and multiplayer experiences has made them a dominant force in PC gaming and esports.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Activision', 'role' => 'publisher', 'image' => '11.jpg', 'description' => 'Activision, founded in 1979, is a major video game publisher, known for popular franchises such as Call of Duty, Tony Hawk\'s Pro Skater, and Crash Bandicoot. The company is a leader in the gaming industry, producing both blockbuster titles and nurturing gaming innovation through strategic acquisitions.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Infinity Ward', 'role' => 'developer', 'image' => '12.jpg', 'description' => 'Infinity Ward, established in 2002, is a key developer of the Call of Duty franchise. Known for its pioneering work in the first-person shooter genre, Infinity Ward has produced some of the most successful and influential military FPS titles, shaping modern gaming with their innovative multiplayer and campaign modes.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Raven Software', 'role' => 'developer', 'image' => '13.jpg', 'description' => 'Raven Software, founded in 1990, is a game development studio best known for its work on the Hexen and Heretic series, as well as contributions to the Call of Duty franchise. A subsidiary of Activision, Raven focuses on first-person shooters and expanding established game franchises.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'The Pokémon Company', 'role' => 'publisher', 'image' => '14.jpg', 'description' => 'The Pokémon Company, founded in 1998, is responsible for managing the Pokémon brand, including games, TV shows, movies, and merchandise. A collaboration between Nintendo, Game Freak, and Creatures, it has become one of the world\'s most successful and enduring entertainment franchises in history.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Nintendo', 'role' => 'publisher', 'image' => '15.png', 'description' => 'Nintendo, founded in 1889, is a legendary video game company known for creating iconic franchises such as Super Mario, The Legend of Zelda, and Pokémon. Nintendo revolutionized gaming with the NES and continues to innovate with consoles like the Switch, blending portability and home gaming.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Game Freak', 'role' => 'developer', 'image' => '16.png', 'description' => 'Game Freak, founded in 1989, is best known as the developer behind the Pokémon series. As a key partner of The Pokémon Company, Game Freak has crafted the core Pokémon games, shaping the franchise\'s success and making it a cornerstone of global pop culture.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Mojang Studios', 'role' => 'publisher', 'image' => '17.jpg', 'description' => 'Mojang Studios, founded in 2009, is the developer behind the globally popular game Minecraft. The studio revolutionized sandbox gaming by allowing players to build, explore, and survive in a blocky, procedurally generated world. Mojang continues to expand Minecraft with updates and community-driven content.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp],
            ['name' => 'Mojang Studios', 'role' => 'developer', 'image' => '17.jpg', 'description' => 'Mojang Studios, founded in 2009, is the developer behind the globally popular game Minecraft. The studio revolutionized sandbox gaming by allowing players to build, explore, and survive in a blocky, procedurally generated world. Mojang continues to expand Minecraft with updates and community-driven content.', 'created_at' => $currentTimeStamp, 'updated_at' => $currentTimeStamp]
        ]);
    }
}